### ISSUE TITLE
package title

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/chirps#10]
For discussion. 

Given that the data are mainly known by the acronym, CHIRPS, should we consider shortening the package title in DESCRIPTION to make it more readable and easier to identify?

Current:
`API Client for the Climate Hazards Group InfraRed Precipitation with Station Data`

Proposed:
`API Client for CHIRPS` 

or
`CHIRPS API Client`

I'm bringing this up because I honestly wouldn't know what the package was from the current title given that I only knew the data as "CHIRPS".

**Comment by kauedesousa** [comment]
Agree with you. I will change to 

`chirps: API Client for CHIRPS`

**Comment by kauedesousa** [comment]
Fixed here https://github.com/agrobioinfoservices/chirps/commit/fa5ca50152df7dc0f7aed0e1f46931d151642938. As `chirps: API Client for CHIRPS`
