### ISSUE TITLE
outputs as data.table

### ISSUE THREAD

**Issue by kauedesousa** [ropensci/chirps#11]
`get_chirps` and `precip_indices` may return large data sets that can cost some memory. Check if is wise and acceptable by users to return a `data.table` object instead of a `tbl_df`.

**Comment by adamhsparks** [comment]
I've started using data.table in most of my packages. This is a valid thought. You can import the whole package, data.table, with little overhead and no other dependencies.

**Comment by adamhsparks** [comment]
I should add. Some might balk at importing the whole package. I don't see an issue in this case, but there are cases to be made against it.

**Comment by kauedesousa** [comment]
I've added a `print()` method `print.chirps_df()` which basically resembles the data.table method. 34aff04. 

Like this

```
#>          id    lon   lat       date chirps
#>       <int>  <dbl> <dbl>     <date>  <dbl>
#> 1:        1 -55.03 -3.80 2013-01-01   0.00
#> 2:        1 -55.03 -3.80 2013-01-02  12.05
#> 3:        1 -55.03 -3.80 2013-01-03  24.11
#> 4:        1 -55.03 -3.80 2013-01-04   0.00
#> 5:        1 -55.03 -3.80 2013-01-05   0.00
#> ---                                       
#> 6569:     3 -55.03 -3.41 2018-12-27   0.00
#> 6570:     3 -55.03 -3.41 2018-12-28   0.00
#> 6571:     3 -55.03 -3.41 2018-12-29   0.00
#> 6572:     3 -55.03 -3.41 2018-12-30   0.00
#> 6573:     3 -55.03 -3.41 2018-12-31   0.00
```

So now the function returns a data.frame and the user decides if s/he uses tibble or data.table
