### ISSUE TITLE
Move CI from Travis to Actions?

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/chirps#16]
I was thinking to move the CI here to GitHub using Actions.

There are issues with installing some of the geo packages for the devel version of R with that though, but you can easily test Windows, macOS and Linux in one spot.

Are you OK with this, @kauedesousa?

**Comment by kauedesousa** [comment]
Yes I am ok with this. Never used before, so it will nice to see how it works.

**Comment by adamhsparks** [comment]
Working! https://github.com/agrobioinfoservices/chirps/actions/runs/113737382

![R-CMD-check](https://github.com/agrobioinfoservices/chirps/workflows/R-CMD-check/badge.svg)

**Comment by kauedesousa** [comment]
this is great! And seems less complicated than Travis when integrating with geo pkgs
