### ISSUE TITLE
get_chips local

### ISSUE THREAD

**Issue by kauedesousa** [ropensci/chirps#18]
Maybe we could write a function to download chirps from the ftp server as an alternative service to `get_chirps()`.  What do you think @adamhsparks ?

**Comment by adamhsparks** [comment]
Are you thinking to just use R as an FTP client only and download the files without loading them in the current R session?

**Comment by adamhsparks** [comment]
Or are you suggesting something like [`reformat_GSOD()`](https://docs.ropensci.org/GSODR/reference/reformat_GSOD.html) that works on local files only and doesn't download?

**Comment by kauedesousa** [comment]
Any solution that will help users (including myself) in piping this data into analyses for large areas (regions, continents). My first idea was an FTP client only and download the files to the disk. I tried `get_GSOD()` and it seems also a nice approach.

But I am not sure if this distracts for the main purpose of the package. Ideally ClimateSERV could provide a service like NASA Power were we fetch the data for a region using bbox and then we just assign the values for the lonlat provided by the users (like I do in `climatrends` when it uses `nasapower`).

**Comment by kauedesousa** [comment]
I've consulted ClimateSERV here https://github.com/SERVIR/ClimateSERV/issues/3

**Comment by adamhsparks** [comment]
I think keeping it as just a client is ideal. It keeps our responsibilities for the package simple.

*Tangent* I'm working on simplifying `nasapower` further to only fetch data and not write any specialised file formats. There's a DSSAT R package and a new APSIM package coming along that users can use if they desire something like that.

**Comment by kauedesousa** [comment]
Great!

**Comment by kauedesousa** [comment]
This issue is solved with this alternative https://github.com/ropensci/chirps/issues/28
