### ISSUE TITLE
Error: lexical error: invalid string in json text.

### ISSUE THREAD

**Issue by kauedesousa** [ropensci/chirps#2]
This error occur when data from a large time series is requested (> 1 year). The problem may be in parsing the json file within the function. When I run the code line by line it works perfectly, and returns the chirps data. It also works in the browser.  

When chirps is required for a time series of ~ 1 year it works well. But this might be a problem for users trying to capture a full picture of a time series. 

````
set.seed(1232)
lonlat <- data.frame(lon = runif(2, -55, -54), lat = runif(2, -3, -2.7))

dates <- c("1982-01-01","2000-12-31")

get_chirps(lonlat, dates)


 Error: lexical error: invalid string in json text.
                                       need to send id
                     (right here) ------^ 
5. parse_string(txt, bigint_as_char) 
4. parseJSON(txt, bigint_as_char) 
3. parse_and_simplify(txt = txt, simplifyVector = simplifyVector, 
    simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, 
    flatten = flatten, ...) 
2. jsonlite::fromJSON(d) at get_chirps.R#154
1. get_chirps(lonlat, dates) 


````

**Comment by adamhsparks** [comment]
I'm poking around and familiarising myself with the package. Will update you if I find anything useful.

Right now I'm overseas, heading home tomorrow.

**Comment by adamhsparks** [comment]
I think I've got it!

The server has a lag between when the request is sent and the data are generate/available for download.

I've added a branch, adam, that has a fix in it, https://github.com/agrobioinfoservices/chirps/blob/d6d0f07a3455250cfd93d2a54f647d99ca4d0320/R/internal_functions.R#L146

It's a crude fix but it illustrates the problem and I think I know how to fix it properly. I just used a `Sys.sleep()` with the example here, 20 seconds is more than enough. But for a larger set it probably won't be so we'll need to use the `getDataRequestProgress` option, https://climateserv.readthedocs.io/en/latest/api.html#getdatarequestprogress, and monitor using `while()` perhaps? And once it's down to "0" or whatever means it's ready, then we can go ahead and fetch the data.

My branch uses `crul` in place of `httr` but I also pushed to `master` and have included the same fix on line 91 of get_chirps.R. https://github.com/agrobioinfoservices/chirps/blob/738e970fbab4d96f2aa9939b8e726fc3a9ce5070/R/get_chirps.R#L91 My branch also has some improvements for the documentation formatting, etc. that we can discuss.

**Comment by kauedesousa** [comment]
Great! I will take a look. I also found yesterday that this problem only happens in Windows. I tried a MacOS and it goes very well. I  changed the way to make the request by using `readLines` which reduce dependencies. It is implemented in the current commit. What do you think about that?

**Comment by adamhsparks** [comment]
FYI I'm only using macOS and Linux and have the issue with both of them.

I'm all for reducing dependencies. It makes your job as a maintainer easier since there are less changes to deal with externally aside from the API itself, which is often enough.

**Comment by adamhsparks** [comment]
I don't see what you refer to changing to readLines when I look at the code? httr or crul are still necessary to interface with the API, no?

**Comment by kauedesousa** [comment]
I forgot to commit the changes, sorry. It is all updated now. I've got the idea of `readLines` from this issue in [stackoverflow](https://stackoverflow.com/questions/49173967/trouble-using-jsonlites-fromjson-with-url-in-r)

**Comment by billyz313** [comment]
You should always use the getDataRequestProgress, it starts at 0 percent complete and continues to 100 percent when it is finished processing the request on the server.  If you continue pinging the server with a time interval until it gets to 100 you will be sure that the data is ready in all cases.

**Comment by adamhsparks** [comment]
Thanks. I wasn't sure which way it went but mentioned using it with while(). That's useful

--
Dr Adam H. Sparks
Associate Professor of Field Crops Pathology  |  Centre for Crop Health
Institute for Life Sciences and the Environment (ILSE)  |  Research and Innovation Division
University of Southern Queensland | Toowoomba, Queensland | 4350 | Australia

Phone: +61746311948
Mobile: +61415489422
Mobile: +61415489422

**Comment by adamhsparks** [comment]
I've worked at adding a repeat loop in to check progress, but now no matter what I do. The function was working at one point with the `Sys.sleep()` but now it fails. I get the same error about needing to send an ID with either method. The progress request only returns an error value, `-1`, I've never had success checking progress yet.

**Comment by kauedesousa** [comment]
I managed to make it work. Now, there is an internal function to check the progress

https://github.com/agrobioinfoservices/chirps/blob/3760fd0f510b115c732ddd2f371f0980f88a919f/R/internal_functions.R#L180

I've added a `while` condition to hold the process until the request is 100% done. And a "funny" `cat` message is added (which can be removed).  https://github.com/agrobioinfoservices/chirps/blob/3760fd0f510b115c732ddd2f371f0980f88a919f/R/get_chirps.R#L92

**Comment by billyz313** [comment]
@adamhsparks There was an issue with the ClimateSERV server over the holidays which was causing the error you were getting.  It should be running fine again and your code should work.

**Comment by adamhsparks** [comment]
Thanks, @billyz313, I was rather confused. We've got it working now.

**Comment by kauedesousa** [comment]
I think we are done with this issue 🥇
