### ISSUE TITLE
Offer alternative datasets from ClimateServ, like IMERG

### ISSUE THREAD

**Issue by xuxoramos** [ropensci/chirps#21]
Given that ClimateServ's precipitation data has stopped updating around May 14th, and that IMERG has recently been added, and that, according to [this paper and its lit review](https://www.researchgate.net/publication/331563685_Assessment_of_Satellite-Based_Precipitation_Measurement_Products_over_the_Hot_Desert_Climate_of_Egypt), IMERG is more accurate than CHIRPS (but less accurate than JAXA's GSMaP), I would suggest making this package more flexible in order to download other datasets, like corrected CHIRPS and IMERG.

I wouldn't change the logo, though. It works quite nice for stickers and stuff like that.

**Comment by kauedesousa** [comment]
Thanks! @xuxoramos, I will check this with @adamhsparks. But I think that the most reasonable solution is to add a new function to fetch the IMERG. I will check the API.

**Comment by adamhsparks** [comment]
Always room for more functions.

**Comment by kauedesousa** [comment]
I have added the function `get_imerg()` and indeed it returns a very different rainfall data. Yet, I still rely on CHIRPS. 

```
library("ggplot2")
library("chirps")

lonlat <- data.frame(lon = c(-55.0281,-54.9857),
                     lat = c(-2.8094, -2.8756))

dates <- c("2017-12-15", "2017-12-31")

dt <- get_imerg(lonlat, dates)

dt2 <- get_chirps(lonlat, dates)


names(dt)[names(dt)=="imerg"] <- "value"
names(dt2)[names(dt2)=="chirps"] <- "value"

dt$id <- paste0("imerg", dt$id)
dt2$id <- paste0("chirps", dt2$id)

d <- rbind(dt, dt2)

ggplot(d, aes(x = date, y = value, group = id, color = id)) +
  geom_line()

```

![image](https://user-images.githubusercontent.com/29840771/86243534-d9b98200-bba6-11ea-93d6-2fdb0758b391.png)

**Comment by kauedesousa** [comment]
Well, it seems that IMERG is for rainfall accumulation. That may be the reason for the high peaks in the chart.
