### ISSUE TITLE
prepare for CRAN submission

### ISSUE THREAD

**Issue by kauedesousa** [ropensci/chirps#22]
Check for any possible issue before sending to CRAN. What to you think @adamhsparks ?

**Comment by adamhsparks** [comment]
Sounds good. I just ran a few preflight checks and fixed a few issues that I found.

I assume you'll be using `devtools::release()`?

**Comment by kauedesousa** [comment]
Submitted. I never used `devtools::release()`, but I found fantastic! I am waiting for CRAN comments.

**Comment by adamhsparks** [comment]
Yes, the checks are extremely useful.
