### ISSUE TITLE
chirps stuck at the example.

### ISSUE THREAD

**Issue by CarlosAndres12** [ropensci/chirps#26]
I don't know if i am doing something wrong, but i am stuck at the example for the past 30 minutes.

![image](https://user-images.githubusercontent.com/8310276/107850293-5cf2b580-6dcf-11eb-9eb5-dded7094b1b4.png)

Is there something that i can check?

Thanks.

**Comment by billyz313** [comment]
I confirmed that CHIRPS was stuck.  I restarted the system, please try again to confirm that it works for you now.

**Comment by CarlosAndres12** [comment]
> I confirmed that CHIRPS was stuck. I restarted the system, please try again to confirm that it works for you now.

It solved the issue thanks!
