### ISSUE TITLE
get_chirps as a S3 method

### ISSUE THREAD

**Issue by kauedesousa** [ropensci/chirps#3]
From R. Bivand comments. 

Write `get_chirps` as a S3 method that can behave different depending on which input is provided. `sf` object, `geojson` or `data.frame`.

**Comment by adamhsparks** [comment]
Doable. Gives me ideas for `nasapower`

**Comment by kauedesousa** [comment]
Great! I've started with the default method. Let's check for stability.

**Comment by adamhsparks** [comment]
I'm out for a few days. Will be back to work early next week

**Comment by adamhsparks** [comment]
Where are we with this? Is it stable or do we need to work to finalise?

**Comment by kauedesousa** [comment]
It is stable for 'data.frame' and 'sf'. I am still thinking in how to deal with 'geojson' since I am still getting acquainted with this format. But for the moment the function `.GET` works with a list of geojson Polygons which cannot be recognised by get_chirps.geojson (since it is a list). 

My idea for now is restrict the method `get_chirps.geojson` to a geojson Multipolygon and do the conversions to a list of geojson Polygons internally. But I still have to study how these classes behaves in R.

**Comment by kauedesousa** [comment]
I've started some code for `get_chirps.geojson` here 

https://github.com/agrobioinfoservices/chirps/blob/694c9cdef6b4c9acecd06abfbe781514f4216355/R/get_chirps.R#L185

But I removed from v0.0.4 to avoid crap code. I will return to this as soon as I get a better idea on how to deal with it.

**Comment by adamhsparks** [comment]
If you'd like, we can make a branch just for this feature to keep working on it and keep master clean, or just a development branch in general to work on new features and merge them into master when they're mature enough for release.

**Comment by kauedesousa** [comment]
I think is a good idea. Just created a 'development' branch

https://github.com/agrobioinfoservices/chirps/tree/devel

**Comment by kauedesousa** [comment]
I've added some improvements in the methods of class 'sf' and 'geojson' in `get_chirps` and `get_esi`. I restricted the methods to accept only geometries of type 'POINT' and 'POLYGON' in `sf` and 'Point' and 'Polygon' in `geojson`. Also I added a control point were only geojson with a geometry tag are accepted. 

https://github.com/agrobioinfoservices/chirps/commit/487c88118544a36b3f3833c6c08a6003e097ecbe

Later we can work on how to deal with geometries of type 'MultiPoint' and 'MultiPolygon'.

**Comment by billyz313** [comment]
Have you tested POINT with the system?  I believe you must buffer the point to a polygon for it to work.

**Comment by kauedesousa** [comment]
Yes, we create a small buffer around the `Point` and coerce the buffer quadrants into a geojson `Polygon`. The buffer also helps us in preventing `NA`s in ESI for cloudy areas. The user just need to increase the buffer distance. 

When the user give us a `Polygon` as 'sf' or 'geojson' it goes directly to the query as it is.

**Comment by billyz313** [comment]
Perfect, nice job!
