### ISSUE TITLE
Make it easier to load the test data outside of tests?

### ISSUE THREAD

**Issue by maelle** [ropensci/chirps#33]
E.g. by putting it in `tests/testthat/` and using `testthat::test_path("test_data.rda")` to find the right path (which works inside and outside of tests).

**Comment by adamhsparks** [comment]
I was not aware of this, but thought maybe there was a better way. 🙏

**Comment by maelle** [comment]
That testthat function is actually the inspiration for [`vcr::vcr_test_path()`](https://docs.ropensci.org/vcr/articles/debugging.html#prepare-your-debugging-environment-1), so handy!
