### ISSUE TITLE
Chirps/UCSB changed its urls - get_chirps returns null for rainfall

### ISSUE THREAD

**Issue by eggenm** [ropensci/chirps#39]
In the last couple weeks, the url changed for chirps. No get_chirps does not return any values for rainfall. It returns -9999 . This is the new https url, as I understand it:
https://data.chc.ucsb.edu/products/CHIRPS-2.0/

**Comment by eggenm** [comment]
Maybe its not the url, but something changed. I also tried the example code and the vignette (returned sf related warnings) to take my code out of the mix and still got -9999:


> library("chirps")
> 
> lonlat <- data.frame(lon = c(-55.0281,-54.9857, -55.0714),
+                      lat = c(-2.8094, -2.8756, -3.5279))
> 
> dates <- c("2017-01-01", "2017-12-31")
> 
> dat <- get_chirps(lonlat, dates)
Getting your request...

> dat
         id    lon   lat       date   chirps
      <int>  <dbl> <dbl>     <date>    <dbl>
1:        1 -55.03 -2.81 2017-01-01 -9999.00
2:        1 -55.03 -2.81 2017-01-02 -9999.00
3:        1 -55.03 -2.81 2017-01-03 -9999.00
4:        1 -55.03 -2.81 2017-01-04 -9999.00
5:        1 -55.03 -2.81 2017-01-05 -9999.00
---                                         
1091:     3 -55.07 -3.53 2017-12-27 -9999.00
1092:     3 -55.07 -3.53 2017-12-28 -9999.00
1093:     3 -55.07 -3.53 2017-12-29 -9999.00
1094:     3 -55.07 -3.53 2017-12-30 -9999.00
1095:     3 -55.07 -3.53 2017-12-31 -9999.00

**Comment by kauedesousa** [comment]
Dear @eggenm thanks for reporting the issue. This is a change in the API provider. Unfortunately we weren’t able to make the update in the package. I plan to do it in the next week. Sorry if this may cause any delays in your planned tasks using the package. 

K

**Comment by eggenm** [comment]
No worries, Thank you!  I appreciate it.

**Comment by kauedesousa** [comment]
Hi @eggenm please look the comment on this issue #40
