### ISSUE TITLE
date 1981-01-01 is not available

### ISSUE THREAD

**Issue by hydroversebr** [ropensci/chirps#50]
Hello!

First of all, thanks for the package. It's very usefull.

I realized that day 1981-01-01 is not available. Its just one date, so i don´t know if matters to you.

Best whishes

![image](https://github.com/ropensci/chirps/assets/108692530/e17cb01c-4c79-4167-9d26-fa5b18187d5a)

**Comment by peetmate** [comment]
it would be useful to fix this

**Comment by egarciag19** [comment]
Hello everyone, is there any solution to this problem in "get_chirps"?, I can not download the data for january 01 1981.

Regards
Erick
