### ISSUE TITLE
Tests need to be more specific and CRAN friendly

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/chirps#7]
Tests requiring connectivity need to use `skip_on_cran()`.

Some tests could be written to be more specific for checking results from the query to ensure that the function is working properly.

**Comment by adamhsparks** [comment]
Tests now use `skip_on_cran()`. Will wait for any reviewer feedback for further changes

**Comment by kauedesousa** [comment]
Adam's comment in this issue https://github.com/agrobioinfoservices/chirps/issues/5, but which should work here as well. 

>The tests use skip_on_cran() due to CRAN policies for Internet connectivity. You'll get a nastygram and have the package pulled if the test fails due to this so I just skip them on CRAN. Ideally webmocking would help with this. I tried to use and eventually failed/gave up with nasapower to use VCR, https://docs.ropensci.org/vcr/. But still I'd encourage us to look at implementing this in the tests. I'll try to have another go at it with chirps and see if I can get it to work properly.

**Comment by kauedesousa** [comment]
I've made some improvements in the main functions. Downloaded data from ClimateSERV and compared with the ones retrieved by the functions. But I don't test for all S3 methods, which makes the codecov a bit low. But I think that for now the most important part is covered, the functions return/compute the right values.

**Comment by adamhsparks** [comment]
I've tried to use vcr in our tests over the weekend. It doesn't work, it's not us, it's vcr.

I've opened an issue, https://github.com/ropensci/vcr/issues/147.

My changes are in the devel branch right now until it stabilises.

**Comment by adamhsparks** [comment]
vcr now works with the coming 0.5 release that's been submitted to CRAN. This is implemented in the devel branch until vcr is on CRAN, then I'll merge with master.

**Comment by adamhsparks** [comment]
@kauedesousa, coverage for `get_ESI()` is a bit low, do we need to improve that?

**Comment by kauedesousa** [comment]
Sorry for the long silence. Yes, lets make more tests for `get_ESI()`. The next days I will work on the comments provided in the last review and check that as well.

**Comment by adamhsparks** [comment]
No worries. Given all that’s going on I was more concerned for your health than for the package. Hope all is well with you.

**Comment by kauedesousa** [comment]
I am doing fine so far. I've addressed the comments from [reviewer 2](https://github.com/agrobioinfoservices/chirps/blob/master/reviewer_comments/reviewer2_comments.md). If you can, please take a look, and let me know if you agree in submitting the reviewed pkg.
