### ISSUE TITLE
Review use of supressWarnings()

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/chirps#8]
In queries to the server it is very useful to capture warnings and communication from the server. If we are suppressing them, that's not the most ideal. 

I'm all for slimming dependencies but using {httr} or {crul} isn't a bad thing here, I don't think, since they're designed for this and allow for further functionality like checking the server for a response before sending the query and stopping the function to let the user know the server isn't responding, etc.

For comment and discussion.

If I were your reviewer I'd suggest using one of these packages to remove this portion of the code and gain added functionality (web mocking, etc.).

**Comment by kauedesousa** [comment]
Agree with you. The idea was to make it simple. But is nice to take advantage of {crul}. 

I've added the code you wrote in https://github.com/agrobioinfoservices/chirps/commit/8de5b5b5408c4ca00cde38504ac933b713087562 into the internal functions https://github.com/agrobioinfoservices/chirps/commit/4006ef2d17b146b5e15fed6239b866455531c789

**Comment by adamhsparks** [comment]
I've cleaned up the queries and made the code more specific for each query, as well as adding more checks for errors coming from the server.
